const FileExplorerConstants = {
    UPDATE_PATH : "UPDATE_PATH",
    SET_PATH : "SET_PATH ",
    SET_PATH_TREE : "SET_PATH_TREE",
    UPDATE_PATH_TREE : "UPDATE_PATH_TREE",
    LOAD_FILES: "LOAD_FILES",
    FILE_LOADING_IN_PROGRESS: "FILE_LOADING_IN_PROGRESS",
    FILE_LOADING_IN_SUCCESS: "FILE_LOADING_IN_SUCCESS",
    SET_ACTION_MENU_VISIBILITY: "SET_ACTION_MENU_VISIBILITY",
    SET_ACTION_MENU_POSITION: "SET_ACTION_MENU_POSITION",
    SET_SELECTED_FILE: "SET_SELECTED_FILE",
    SHOW_INFO_MODAL: "SHOW_INFO_MODAL",
    SET_FILES: "SET_FILES",
    NAVIGATE_IN_PATH_BY_INDEX: "NAVIGATE_IN_PATH_BY_INDEX",
    SET_SEARCH_FILTER:"SET_SEARCH_FILTER",
    SHOW_CREATE_MODAL:"SHOW_CREATE_MODAL"
}

export default FileExplorerConstants


export const MenuConstant = {
    OPEN: "OPEN",
    GET_INFO: "GET_INFO",
    DELETE: "DELETE"
}